### ISSUE TITLE
#3 の LT 募集

### ISSUE THREAD

**Issue by kozo2** [PyDataOsaka/pydata-osaka-2017#1]
https://www.meetup.com/ja-JP/PyData-Osaka/events/236296769

でのLTを望まれる方はコメントをお願いいたします．

**Comment by taku-y** [comment]
時間があれば変分ベイズの話をしたいと思います:
https://github.com/taku-y/presentation/blob/master/20170117-pydata-osaka/20161127-pydata-osaka-pymc3-variational.ipynb

多くの人が発表する方が良いと思いますので、他に（当日でも）発表したい方がいらっしゃれば次回以降に回して頂いて構いません。

**Comment by kozo2** [comment]
@taku-y はい，ぜひおねがいします．無理に休憩をたくさん入れたのでリスケすると問題ないと思います．

**Comment by taku-y** [comment]
ご了承ありがとうございます。よろしくお願いいたします。

**Comment by kozo2** [comment]
@taku-y さん
発表の模様をYouTubeでライブストリーミング配信させてもらっても問題無いでしょうか?
問題無い場合，ご発表は私のラップトップを使っていただくことになるのですが
https://github.com/taku-y/presentation/blob/master/20170117-pydata-osaka/20161127-pydata-osaka-pymc3-variational.ipynb
のrunに必要なjupyter extensionはありますでしょうか

**Comment by taku-y** [comment]
@kozo2 配信OKです。次のDockerの環境で動作を確認しています：https://github.com/taku-y/dockerfiles/tree/master/rise

**Comment by kozo2** [comment]
@taku-y 配信許可ありがとうございます．またDockerfileありがとうございます．buildしておきます
